version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      TELEGRAM_BOT_TOKEN: "7117388468:AAHuSG6GnsbpKj1FL2sQkDJkQzgi5HBTiko"
      TELEGRAM_CHAT_ID: "6298447721"

  dashboard:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    command: streamlit run dashboard/app.py
    ports:
      - "8501:8501"
    depends_on:
      - api
